### PR TITLE
[CLI-1054] Set connection timeout for appc use command

### PR DESCRIPTION
**Pull request by feons**
https://jira.appcelerator.org/browse/CLI-1054

### CODE REVIEW

**Comment by kolipakakondal** [comment]
@feons  -  This looks good. At least it will return the error message at the end of 5 attempts. However, it doesn't resolve the real problem from the user point of view, it took around 6mins to return the error message and I'm sure no one will wait till that time, rather they will kill the process(CLI/Studio) after 1min or so. Can we optimize it further?

**Comment by feons** [comment]
@kolipakakondal, I don't understand how could it take 8mins to do get the error message. I did a time, it takes roughly 0m8s.

**Comment by cheekiatng** [comment]
not critical but https://github.com/appcelerator/appc-install/blob/master/lib/util.js#L555 should use `MAX_RETRIES`

**Comment by kolipakakondal** [comment]
@feons  - reverified again today! - it's taking close to 8mins :-(

**Comment by kolipakakondal** [comment]
```
  appc:util request {"url":{"protocol":"https:","slashes":true,"auth":null,"host":"software.appcelerator.com","port":443,"hostname":"software.appcelerator.com","hash":null,"search":null,"query":null,"pathname":"/api/appc/install/trace","path":"/api/appc/install/trace","href":"https://software.appcelerator.com/api/appc/install/trace"},"headers":{"user-agent":"Appcelerator CLI/4.2.6 (darwin)","host":"software.appcelerator.com","appc-token":"s:GqDiRyuS6qHnupqxkvBeuoMa03FrTkb9./sISAK8UElE6AWD6AvizyrChitHmfQFPoiOmTiMKMZ8"},"proxy":"https://username:password@10.10.12.13:4567"} +190ms
|  appc:util request error +1m { [Error: tunneling socket could not be established, cause=connect ETIMEDOUT] code: 'ECONNRESET' }
```
From above, after a request, it took more than a min to return the error message

**Comment by feons** [comment]
@kolipakakondal, added timeout, please test again. Thank you!

**Comment by kolipakakondal** [comment]
Looks good to me, it took around 2min 30sec to return the error.

**Pull request merged**
