### PR TITLE
[CLI-1003] If you run "appc setup" with the help flag, then "appc setup" will try to find/download the latest core first

### PR DESCRIPTION
**Pull request by janvennemann**
JIRA: https://jira.appcelerator.org/browse/CLI-1003

### CODE REVIEW

**Comment by cheekiatng** [comment]
@janvennemann Functionally tested. it no longer try to install latest first and shows the help prompt. However, it also shows `error: unknown option --help`
See trace here:
```
AppcAdmins-MacBook-Pro-3:~ kiat$ appc setup --help

  Usage: setup [options]

  called to setup your environment

  Options:

    -h, --help                         output usage information
    --dashboard <dashboard>            the dashboard url to use for logins
    -l, --log-level <level>            change log level
    -o, --output <format>              format output [only "json" is supported]
    -v, --version                      output the version of the cli [if -o "json", the version of npm will also be output]
    -q, --quiet                        reduce the amount of text output to the console
    --no-banner                        disable banner
    --no-colors                        disable colors
    --no-services                      disable services
    --no-progress, --no-progress-bars  disable progress bars
    --no-prompt                        disable prompt
    --prompt-port <promptPort>         port to use socket-based prompting
    --prompt-type <promptType>         prompt type ["cli","socket","socket-bundle"], defaults to "cli"
    --username <username>              username for login
    --password <password>              password for login
    -e, --env <environment>            environment such as production, preproduction, development, etc
    -o, --org-id <orgId>               organization id for logins
    -P, --plugin-paths <pluginPaths>   comma-separated search paths for plugins
    -r, --registry <registry>          the registry server url to use
    -s, --server <server>              the security server url to use for logins
    -v, --vpc-env <vpcEnv>             vpc environment for logins


  error: unknown option `--help'
```

**Comment by janvennemann** [comment]
This is not directly related to the setup command and a known bug, see https://jira.appcelerator.org/browse/CLI-964.

**Comment by cheekiatng** [comment]
Ok will merge after bumping appc-install

**Comment by cheekiatng** [comment]
APPROVED

**Pull request merged**
