### PR TITLE
[CLI-1115] Set Node 4.x as minimum supported version

### PR DESCRIPTION
**Pull request by feons**
https://jira.appcelerator.org/browse/CLI-1115

### CODE REVIEW

**Comment by cheekiatng** [comment]
CR and FT passed. APPROVED!

**Comment by cheekiatng** [comment]
@feons but i think we need to bump these to have it in 4.2.8 right?
https://github.com/appcelerator/appc-install/blob/master/package.json#L3
https://github.com/appcelerator/appc-install/blob/master/npm-shrinkwrap.json#L3

**Comment by feons** [comment]
@cheekiatng, jenkins doesn't dump this?

**Comment by cheekiatng** [comment]
Oh it does. weird I had the impression it was only app-cli that gets auto bumped. Thanks.

**Pull request merged**
